---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ocsp-forever
  name: ocsp-forever
spec:
  ports:
  - name: "metrics"
    port: 9102
    targetPort: 8080
  selector:
    app: ocsp-forever
status:
  loadBalancer: {}
